# -*- coding: utf-8 -*-

################################################################################
# Form generated from reading UI file 'form.ui'
#
# Created by: Qt User Interface Compiler version 6.8.0
#
# WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
                            QSize)
from PySide6.QtGui import (QAction, QIcon)
from PySide6.QtWidgets import (QMenu, QMenuBar,
                               QScrollArea, QStatusBar, QTextEdit,
                               QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(860, 602)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.actionOpen.setIcon(icon)
        self.actionOpen_with_URL = QAction(MainWindow)
        self.actionOpen_with_URL.setObjectName(u"actionOpen_with_URL")
        self.actionClose_this_document = QAction(MainWindow)
        self.actionClose_this_document.setObjectName(u"actionClose_this_document")
        self.actionSave_Close = QAction(MainWindow)
        self.actionSave_Close.setObjectName(u"actionSave_Close")
        self.actionDiscard_Close = QAction(MainWindow)
        self.actionDiscard_Close.setObjectName(u"actionDiscard_Close")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionSave.setIcon(icon1)
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.actionSave_as.setIcon(icon2)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPrint))
        self.actionPrint.setIcon(icon3)
        self.actionPage_Settings = QAction(MainWindow)
        self.actionPage_Settings.setObjectName(u"actionPage_Settings")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPageSetup))
        self.actionPage_Settings.setIcon(icon4)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentProperties))
        self.actionSettings.setIcon(icon5)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.actionExit.setIcon(icon6)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCut))
        self.actionCut.setIcon(icon7)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCopy))
        self.actionCopy.setIcon(icon8)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditPaste))
        self.actionPaste.setIcon(icon9)
        self.actionFind = QAction(MainWindow)
        self.actionFind.setObjectName(u"actionFind")
        icon10 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditFind))
        self.actionFind.setIcon(icon10)
        self.actionReplace = QAction(MainWindow)
        self.actionReplace.setObjectName(u"actionReplace")
        self.actionGo_to = QAction(MainWindow)
        self.actionGo_to.setObjectName(u"actionGo_to")
        self.actionSelect_all = QAction(MainWindow)
        self.actionSelect_all.setObjectName(u"actionSelect_all")
        icon11 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditSelectAll))
        self.actionSelect_all.setIcon(icon11)
        self.actionAdd_timestamp = QAction(MainWindow)
        self.actionAdd_timestamp.setObjectName(u"actionAdd_timestamp")
        self.actionFont = QAction(MainWindow)
        self.actionFont.setObjectName(u"actionFont")
        self.actionAutomatic_line_wrapping = QAction(MainWindow)
        self.actionAutomatic_line_wrapping.setObjectName(u"actionAutomatic_line_wrapping")
        self.actionFont_2 = QAction(MainWindow)
        self.actionFont_2.setObjectName(u"actionFont_2")
        self.actionZoom = QAction(MainWindow)
        self.actionZoom.setObjectName(u"actionZoom")
        self.actionView_README = QAction(MainWindow)
        self.actionView_README.setObjectName(u"actionView_README")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon12 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.actionNew.setIcon(icon12)
        self.actionTo_UTF_8 = QAction(MainWindow)
        self.actionTo_UTF_8.setObjectName(u"actionTo_UTF_8")
        self.actionTo_GBK = QAction(MainWindow)
        self.actionTo_GBK.setObjectName(u"actionTo_GBK")
        self.actionTo_ANSI = QAction(MainWindow)
        self.actionTo_ANSI.setObjectName(u"actionTo_ANSI")
        self.actionOthers = QAction(MainWindow)
        self.actionOthers.setObjectName(u"actionOthers")
        self.actionOthers_2 = QAction(MainWindow)
        self.actionOthers_2.setObjectName(u"actionOthers_2")
        self.actionGenerate = QAction(MainWindow)
        self.actionGenerate.setObjectName(u"actionGenerate")
        self.actionGenerate_from = QAction(MainWindow)
        self.actionGenerate_from.setObjectName(u"actionGenerate_from")
        self.actionGenerate_2 = QAction(MainWindow)
        self.actionGenerate_2.setObjectName(u"actionGenerate_2")
        self.actionGenerate_from_Selection = QAction(MainWindow)
        self.actionGenerate_from_Selection.setObjectName(u"actionGenerate_from_Selection")
        self.actionGenerate_3 = QAction(MainWindow)
        self.actionGenerate_3.setObjectName(u"actionGenerate_3")
        self.actionGenerate_from_Selection_2 = QAction(MainWindow)
        self.actionGenerate_from_Selection_2.setObjectName(u"actionGenerate_from_Selection_2")
        self.actionGenerate_4 = QAction(MainWindow)
        self.actionGenerate_4.setObjectName(u"actionGenerate_4")
        self.actionGenerate_from_Selection_3 = QAction(MainWindow)
        self.actionGenerate_from_Selection_3.setObjectName(u"actionGenerate_from_Selection_3")
        self.actionEnabled = QAction(MainWindow)
        self.actionEnabled.setObjectName(u"actionEnabled")
        self.actionEnabled.setCheckable(True)
        self.actionDisabled = QAction(MainWindow)
        self.actionDisabled.setObjectName(u"actionDisabled")
        self.actionDisabled.setCheckable(True)
        self.actionDisabled.setChecked(True)
        self.actionSettings_2 = QAction(MainWindow)
        self.actionSettings_2.setObjectName(u"actionSettings_2")
        self.actionPreference_Settings = QAction(MainWindow)
        self.actionPreference_Settings.setObjectName(u"actionPreference_Settings")
        self.actionPreference_Settings.setIcon(icon5)
        self.actionOpen_in_System_File_Explorer = QAction(MainWindow)
        self.actionOpen_in_System_File_Explorer.setObjectName(u"actionOpen_in_System_File_Explorer")
        icon13 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderOpen))
        self.actionOpen_in_System_File_Explorer.setIcon(icon13)
        self.actionOpen_with = QAction(MainWindow)
        self.actionOpen_with.setObjectName(u"actionOpen_with")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon14 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentRevert))
        self.actionUndo.setIcon(icon14)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon15 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditRedo))
        self.actionRedo.setIcon(icon15)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 861, 561))
        self.scrollArea.setMaximumSize(QSize(861, 561))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 10000, 10000))
        self.scrollAreaWidgetContents_2.setMinimumSize(QSize(10000, 10000))
        self.textEdit = QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 0, 10000, 10000))
        self.textEdit.setMinimumSize(QSize(10000, 10000))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 860, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuAutomatic_line_wrapping = QMenu(self.menuView)
        self.menuAutomatic_line_wrapping.setObjectName(u"menuAutomatic_line_wrapping")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuEncode = QMenu(self.menubar)
        self.menuEncode.setObjectName(u"menuEncode")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuMD5 = QMenu(self.menuTools)
        self.menuMD5.setObjectName(u"menuMD5")
        self.menuSHA_1 = QMenu(self.menuTools)
        self.menuSHA_1.setObjectName(u"menuSHA_1")
        self.menuSHA_2 = QMenu(self.menuTools)
        self.menuSHA_2.setObjectName(u"menuSHA_2")
        self.menuSHA_256 = QMenu(self.menuTools)
        self.menuSHA_256.setObjectName(u"menuSHA_256")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuEncode.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Close)
        self.menuFile.addAction(self.actionDiscard_Close)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_in_System_File_Explorer)
        self.menuFile.addAction(self.actionOpen_with)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPage_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreference_Settings)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addAction(self.actionGo_to)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_all)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_timestamp)
        self.menuView.addAction(self.actionFont_2)
        self.menuView.addAction(self.menuAutomatic_line_wrapping.menuAction())
        self.menuAutomatic_line_wrapping.addAction(self.actionEnabled)
        self.menuAutomatic_line_wrapping.addAction(self.actionDisabled)
        self.menuHelp.addAction(self.actionView_README)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEncode.addAction(self.actionTo_UTF_8)
        self.menuEncode.addAction(self.actionTo_GBK)
        self.menuEncode.addAction(self.actionTo_ANSI)
        self.menuEncode.addSeparator()
        self.menuEncode.addAction(self.actionOthers)
        self.menuTools.addAction(self.menuMD5.menuAction())
        self.menuTools.addAction(self.menuSHA_1.menuAction())
        self.menuTools.addAction(self.menuSHA_2.menuAction())
        self.menuTools.addAction(self.menuSHA_256.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionOthers_2)
        self.menuMD5.addAction(self.actionGenerate)
        self.menuMD5.addAction(self.actionGenerate_from)
        self.menuSHA_1.addAction(self.actionGenerate_2)
        self.menuSHA_1.addAction(self.actionGenerate_from_Selection)
        self.menuSHA_2.addAction(self.actionGenerate_3)
        self.menuSHA_2.addAction(self.actionGenerate_from_Selection_2)
        self.menuSHA_256.addAction(self.actionGenerate_4)
        self.menuSHA_256.addAction(self.actionGenerate_from_Selection_3)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        # if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
        # endif // QT_CONFIG(shortcut)
        self.actionOpen_with_URL.setText(QCoreApplication.translate("MainWindow", u"Open with URL...", None))
        self.actionClose_this_document.setText(QCoreApplication.translate("MainWindow", u"Close this document", None))
        self.actionSave_Close.setText(QCoreApplication.translate("MainWindow", u"Save and Close...", None))
        # if QT_CONFIG(shortcut)
        self.actionSave_Close.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
        # endif // QT_CONFIG(shortcut)
        self.actionDiscard_Close.setText(QCoreApplication.translate("MainWindow", u"Discard and Close...", None))
        # if QT_CONFIG(shortcut)
        self.actionDiscard_Close.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+Shift+S", None))
        # endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        # if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
        # endif // QT_CONFIG(shortcut)
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as...", None))
        # if QT_CONFIG(shortcut)
        self.actionSave_as.setShortcut(QCoreApplication.translate("MainWindow", u"F12", None))
        # endif // QT_CONFIG(shortcut)
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print...", None))
        # if QT_CONFIG(shortcut)
        self.actionPrint.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
        # endif // QT_CONFIG(shortcut)
        self.actionPage_Settings.setText(QCoreApplication.translate("MainWindow", u"Page Setup...", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        # if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+Shift+Q", None))
        # endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        # if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
        # endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        # if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
        # endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        # if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
        # endif // QT_CONFIG(shortcut)
        self.actionFind.setText(QCoreApplication.translate("MainWindow", u"Find...", None))
        # if QT_CONFIG(shortcut)
        self.actionFind.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
        # endif // QT_CONFIG(shortcut)
        self.actionReplace.setText(QCoreApplication.translate("MainWindow", u"Replace...", None))
        # if QT_CONFIG(shortcut)
        self.actionReplace.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
        # endif // QT_CONFIG(shortcut)
        self.actionGo_to.setText(QCoreApplication.translate("MainWindow", u"Go to...", None))
        # if QT_CONFIG(shortcut)
        self.actionGo_to.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
        # endif // QT_CONFIG(shortcut)
        self.actionSelect_all.setText(QCoreApplication.translate("MainWindow", u"Select all", None))
        # if QT_CONFIG(shortcut)
        self.actionSelect_all.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
        # endif // QT_CONFIG(shortcut)
        self.actionAdd_timestamp.setText(QCoreApplication.translate("MainWindow", u"Add timestamp", None))
        self.actionFont.setText(QCoreApplication.translate("MainWindow", u"Font...", None))
        self.actionAutomatic_line_wrapping.setText(
            QCoreApplication.translate("MainWindow", u"Automatic line wrapping", None))
        self.actionFont_2.setText(QCoreApplication.translate("MainWindow", u"Font...", None))
        self.actionZoom.setText(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.actionView_README.setText(QCoreApplication.translate("MainWindow", u"View README", None))
        # if QT_CONFIG(shortcut)
        self.actionView_README.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+F1", None))
        # endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        # if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
        # endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New...", None))
        # if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
        # endif // QT_CONFIG(shortcut)
        self.actionTo_UTF_8.setText(QCoreApplication.translate("MainWindow", u"To UTF-8", None))
        self.actionTo_GBK.setText(QCoreApplication.translate("MainWindow", u"To GBK", None))
        self.actionTo_ANSI.setText(QCoreApplication.translate("MainWindow", u"To ANSI", None))
        self.actionOthers.setText(QCoreApplication.translate("MainWindow", u"Others...", None))
        self.actionOthers_2.setText(QCoreApplication.translate("MainWindow", u"Others...", None))
        self.actionGenerate.setText(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.actionGenerate_from.setText(QCoreApplication.translate("MainWindow", u"Generate from Selection", None))
        self.actionGenerate_2.setText(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.actionGenerate_from_Selection.setText(
            QCoreApplication.translate("MainWindow", u"Generate from Selection", None))
        self.actionGenerate_3.setText(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.actionGenerate_from_Selection_2.setText(
            QCoreApplication.translate("MainWindow", u"Generate from Selection", None))
        self.actionGenerate_4.setText(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.actionGenerate_from_Selection_3.setText(
            QCoreApplication.translate("MainWindow", u"Generate from Selection", None))
        self.actionEnabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.actionDisabled.setText(QCoreApplication.translate("MainWindow", u"Disabled", None))
        self.actionSettings_2.setText(QCoreApplication.translate("MainWindow", u"Settings...", None))
        self.actionPreference_Settings.setText(
            QCoreApplication.translate("MainWindow", u"Preference Settings...", None))
        # if QT_CONFIG(shortcut)
        self.actionPreference_Settings.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+Shift+S", None))
        # endif // QT_CONFIG(shortcut)
        self.actionOpen_in_System_File_Explorer.setText(
            QCoreApplication.translate("MainWindow", u"Open in System File Explorer", None))
        self.actionOpen_with.setText(QCoreApplication.translate("MainWindow", u"Open with...", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        # if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
        # endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        # if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
        # endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuAutomatic_line_wrapping.setTitle(
            QCoreApplication.translate("MainWindow", u"Automatic line wrapping", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuEncode.setTitle(QCoreApplication.translate("MainWindow", u"Encode", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuMD5.setTitle(QCoreApplication.translate("MainWindow", u"MD5", None))
        self.menuSHA_1.setTitle(QCoreApplication.translate("MainWindow", u"SHA-1", None))
        self.menuSHA_2.setTitle(QCoreApplication.translate("MainWindow", u"SHA-2", None))
        self.menuSHA_256.setTitle(QCoreApplication.translate("MainWindow", u"SHA-256", None))
    # retranslateUi
